apiVersion: v1
kind: ConfigMap
metadata:
  name: robusta-config
  namespace: robusta
data:
  active_playbooks.yaml: |
    playbook_repos:
      - url: https://github.com/robusta-dev/robusta-playbooks.git
    
    global_config:
      prometheus_url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    
    sinks_config:
      - webhook_sink:
          name: main_webhook
          url: "http://robusta-runner.robusta.svc.cluster.local:5000/api/alerts"
