apiVersion: v1
kind: ConfigMap
metadata:
  name: robusta-config
  namespace: robusta
data:
  active_playbooks.yaml: |
    playbook_repos: {}
    
    global_config:
      cluster_name: home-lab
      prometheus_url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      
    sinks_config: []
    
    active_playbooks:
      - triggers:
          - on_pod_crash_loop:
              restart_reason: "CrashLoopBackOff"
        actions:
          - logs_enricher: {}
      
      - triggers:
          - on_prometheus_alert:
              alert_name: KubePodCrashLooping
        actions:
          - logs_enricher: {}
